### ISSUE TITLE
TODO: Things I still need to do

### ISSUE THREAD

**Issue by W2Wizard** [W2Codam/libft#1]
## TODO:

- [x] `.c` Implementations
- [x] Make file and a basic and further understanding as to how they work
- [x] Ensure files are placed like its asked
- [x] Comments (See if norminette allows them)
- [x] Finish ReadMe
- [x] Finish Bonus
- [x] Implement the bonus itself along with the makefile

**Comment by poes** [comment]
bro its not working lol

**Comment by W2Wizard** [comment]
Finished everything!
